### ISSUE TITLE
LoF for GRCh38: can't locate object method "prepare" ~ gerp_conservation_scores~

### ISSUE THREAD

**Issue by chadohyeon** [konradjk/loftee#47]
Hello,

I've been trying to annotate a GRCh38 *.vcf file with using Loftee
I already downloaded human_ancester_fa* files, loftee.sql.gz (for GRCh38) and
a bigwig file (gerp_conservation_scores.homo_sapiens.GRCh38.bw)

This is my code.

export PERL5LIB=$PERL5LIB:/Users/dcha/.vep/Plugins

/Users/dcha/program/ensembl-vep/vep --assembly GRCh38 --offline --no_stats --tab -i /Users/dcha/program/vep_files/input/hg38_no_annot_2000.vcf -o /Users/dcha/program/vep_files/output/test_for_loftee.txt --canonical --pick --pick_order canonical --plugin LoF,loftee_path:/Users/dcha/.vep/Plugins/,human_ancestor_fa:/Users/dcha/.vep/Plugins/human_ancestor.fa.gz,conservation_file:/Users/dcha/.vep/Plugins/loftee.sql,gerp_bigwig:/Users/dcha/.vep/Plugins/gerp_conservation_scores.homo_sapiens.GRCh38.bw --force_overwrite

By the way, It always gives me the error message as below:

WARNING: Plugin 'LoF' went wrong: Can't locate object method "prepare" via package "gerp_conservation_scores.homo_sapiens.GRCh38.bw" (perhaps you forgot to load "gerp_conservation_scores.homo_sapiens.GRCh38.bw"?) at /Users/dcha/.vep/Plugins/gerp_dist.pl line 82, <__ANONIO__> line 2000.

What should I do to fix this problem?

Thank you for reading this.

**Comment by konradjk** [comment]
Are you using the GRCh38 branch? Make sure to use that one: https://github.com/konradjk/loftee/tree/grch38

**Comment by trptyrphe11** [comment]
No, I am using the one from main page clone https url: https://github.com/konradjk/loftee.git

**Comment by chadohyeon** [comment]
I've fixed it. Thank you!

**Comment by anyunyaohui** [comment]
Could you tell me how to fix it ？ I still have this problem using  https://github.com/konradjk/loftee/tree/grch38. Thanks
